# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.DeveloperEdition.ur
PackageVersion: "148.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/148.0b13/win32/ur/Firefox%20Setup%20148.0b13.exe
  InstallerSha256: 63708E06C797958DEAE0D8729DF9214F3066FBADB83956FAD171E3B560E7590C
  ProductCode: Firefox Developer Edition 148.0 (x86 ur)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/148.0b13/win64/ur/Firefox%20Setup%20148.0b13.exe
  InstallerSha256: B7B6A30E0A000215DD9D7A64D4E396BF63C18B63ED1B8BBA84404E497B493752
  ProductCode: Firefox Developer Edition 148.0 (x64 ur)
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/devedition/releases/148.0b13/win64-aarch64/ur/Firefox%20Setup%20148.0b13.exe
  InstallerSha256: 98A656A79791FC66C0467964ED3647ADCD6DE155877CF423F8271510B5CB3A9F
  ProductCode: Firefox Developer Edition 148.0 (arm64 ur)
ManifestType: installer
ManifestVersion: 1.12.0
